[build]
builder = "nixpacks"
buildCommand = "npm install"

[deploy]
startCommand = "npm run railway"
healthcheckPath = "/rooms"
healthcheckTimeout = 100
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 10 