[build]
builder = "nixpacks"
buildCommand = "npm install && npm rebuild bcrypt --build-from-source"

[deploy]
startCommand = "npm run railway"
healthcheckPath = "/rooms"
healthcheckTimeout = 300
restartPolicy = "always" 